global:
  resolve_timeout: 5m # 알림이 해결되었다고 판단하는 시간

route:
  group_by: ['alertname']
  group_wait: 10s         # 첫 알림 발생 시 대기 시간
  group_interval: 10s     # 동일 그룹의 알림 간 대기 시간
  repeat_interval: 1h     # 동일 알림 반복 간격
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: 'dotoryman@gmail.com'
    from: 'dotoryman@gmail.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: 'dotoryman@gmail.com'
    auth_password: ${GF_SMTP_PASSWORD}
    require_tls: true
    send_resolved: true