version: '3.8'

services:
  django:
    build: ./django
    container_name: django
    env_file: .env
    networks:
      - transcendence
    volumes:
      - django_vol:/home
      - root_vol:/st
    ports:
        - "8000:8000"
        
  nginx:
    build: ./nginx
    container_name: nginx
    env_file: .env
    networks:
      - transcendence
    volumes:
        - nginx_conf:/etc/nginx/conf.d
        - static_vol:/home/staticfiles
    ports:
      - "8080:80"

  postgres:
    image: postgres:17-alpine3.20
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - transcendence
    volumes:
      - postgres_vol:/var/lib/postgresql/data
      - root_vol:/home
    ports:
     - "5432:5432"

networks:
  transcendence:
    name: tsen
    driver: bridge
    
volumes:
  django_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/changhyun/tsen/django/django_vol

  nginx_conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/changhyun/tsen/nginx/nginx_conf

  static_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/changhyun/tsen/django/django_vol/staticfiles

  postgres_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/changhyun/tsen/postgre/postgres_vol

  root_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/changhyun/tsen