# Generated by Django 5.1.4 on 2025-01-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lose_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('playing', 'Playing'), ('in-queue', 'In Queue'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='win_count',
            field=models.IntegerField(default=0),
        ),
    ]
