groups:
- name: service_alerts
  rules:
  # 모니터링 중인 서비스(django, nginx, postgres, redis, exporter들 )가 중단되었는지 감지
  - alert: ServiceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Service {{ $labels.job }} is down"
      description: "Service {{ $labels.job }} has been down for more than 1 minute"
  - alert: RedisDown
    expr: redis_up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Redis is down"
      description: "Redis instance has been down for more than 1 minute"
  - alert: PostgresDown
    expr: pg_up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "PostgreSQL is down"
      description: "PostgreSQL instance has been down for more than 1 minute"
  - alert: NginxDown
    expr: nginx_up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Nginx is down"
      description: "Nginx instance has been down for more than 1 minute"

  # Nginx 클라이언트 에러(400번대) 비율이 10% 이상일 때 경고
  - alert: NginxHighHttp4xxErrorRate
    expr: rate(nginx_http_requests_total{status=~"^4.."}[1m]) / rate(nginx_http_requests_total[1m]) * 100 > 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High HTTP 4xx error rate on Nginx"
      description: "HTTP 4xx error rate is above 10% for the last 5 minutes"
  # Nginx 클라이언트 에러(500번대) 비율이 5% 이상일 때 경고
  - alert: NginxHighHttp5xxErrorRate
    expr: rate(nginx_http_requests_total{status=~"^5.."}[1m]) / rate(nginx_http_requests_total[1m]) * 100 > 5
    for: 3m
    labels:
      severity: critical
    annotations:
      summary: "High HTTP 5xx error rate on Nginx"
      description: "HTTP 5xx error rate is above 5% for the last 3 minutes"

  # PostgreSQL DB 연결이 최대 허용치의 80% 이상 사용될 때 경고
  - alert: PostgresqlHighConnections
    expr: pg_stat_activity_count > pg_settings_max_connections * 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "PostgreSQL high connection usage"
      description: "PostgreSQL instance has used more than 80% of available connections"

  # Redis Redis 메모리 사용량이 90% 이상일 때 경고
  - alert: RedisHighMemoryUsage
    expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Redis high memory usage"
      description: "Redis memory usage is above 90%"

  # Django 평균 응답 시간이 1초 이상일 때 경고
  - alert: DjangoHighResponseTime
    expr: rate(django_http_requests_latency_seconds_sum[5m]) / rate(django_http_requests_latency_seconds_count[5m]) > 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Django high response time"
      description: "Django average response time is above 1 second for the last 5 minutes"

  # CPU 사용률이 80% 이상일 때 경고
  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage"
      description: "CPU usage is above 80% for more than 5 minutes"

  # 메모리 사용률이 85% 이상일 때 경고
  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage"
      description: "Memory usage is above 85%"

  # 디스크 여유 공간이 10% 미만일 때 경고
  - alert: LowDiskSpace
    expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Low disk space"
      description: "Disk space usage is above 90%"